# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezforge < Formula
  desc "Deploy and manage MCP servers on ezForge Platform"
  homepage "https://ezforge.ai"
  version "0.1.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezforgeai/ezforge-cli/releases/download/v0.1.0/ezforge_0.1.0_darwin_amd64.tar.gz"
      sha256 "d08d015dff6ab620f49f2ae5da9f98278fe97141f55aeb596f7fc26c4f493779"

      define_method(:install) do
        bin.install "ezforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezforgeai/ezforge-cli/releases/download/v0.1.0/ezforge_0.1.0_darwin_arm64.tar.gz"
      sha256 "2f0fab2ec483818db6ce2799bc9c6c9991bf50ccfc755facb1b0257df3e6b86d"

      define_method(:install) do
        bin.install "ezforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezforgeai/ezforge-cli/releases/download/v0.1.0/ezforge_0.1.0_linux_amd64.tar.gz"
      sha256 "e17b5847b9e8eae3ae541af1ac89d702baae10d6a309667caf23bc4014c9d255"
      define_method(:install) do
        bin.install "ezforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezforgeai/ezforge-cli/releases/download/v0.1.0/ezforge_0.1.0_linux_arm64.tar.gz"
      sha256 "02f133c107337f5f51d649322e71efee313a2b7b64f69f0ccb58e9c9be5195e0"
      define_method(:install) do
        bin.install "ezforge"
      end
    end
  end

  test do
    system "#{bin}/ezforge", "--help"
  end
end
