# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezforge < Formula
  desc "Deploy and manage MCP servers on ezForge Platform"
  homepage "https://ezforge.ai"
  version "0.1.0"
  license "UNLICENSED"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ezforgeai/ezRyder/releases/download/v0.1.0/ezforge_0.1.0_darwin_amd64.tar.gz"
      sha256 "8903f4c029c5a06dbe6a734449dc81c1efdd68d7fade02fb98250e35548e392a"

      define_method(:install) do
        bin.install "ezforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ezforgeai/ezRyder/releases/download/v0.1.0/ezforge_0.1.0_darwin_arm64.tar.gz"
      sha256 "eeb8abd11d5660c59b813633befbc55988e2a6d2346bc9bfe212f6ab0dd8123e"

      define_method(:install) do
        bin.install "ezforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezforgeai/ezRyder/releases/download/v0.1.0/ezforge_0.1.0_linux_amd64.tar.gz"
      sha256 "6bf2c98ff4d9762246edc9fa5ecb85bdd42335c6e5b077a73916d31617843a0f"
      define_method(:install) do
        bin.install "ezforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ezforgeai/ezRyder/releases/download/v0.1.0/ezforge_0.1.0_linux_arm64.tar.gz"
      sha256 "d7754a0f416036e928f07a714095587ffabdb42aea57ca998a48739e6d61a2da"
      define_method(:install) do
        bin.install "ezforge"
      end
    end
  end

  test do
    system "#{bin}/ezforge", "--help"
  end
end
